Dockerfile
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/RtdMsEnrolledPaymentInstrumentAppTest.java
src/test/resources/application-test.yml

This PR provides basic microservice structure with default configuration files
- added empty microservice skeleton

[RTD-294] Repository setup

---

manifests/deployment.yml

[RTD-493] disabled k8s liveness and readiness

---

src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/adapters/event/KafkaAdapter.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/application/EnrolledPaymentInstrumentService.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/persistence/repositories/EnrolledPaymentInstrumentRepositoryImpl.java

This PR improve error logging on mongodb write operations.

Improved error logging

---

.github/workflows/anchore.yml

This PR adds anchore scan workflow

Anchore scan workflow

---

Dockerfile
manifests/deployment.yml
pom.xml
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/RtdMsEnrolledPaymentInstrumentApplication.java

[RTD-539] K8S manifest update - producer config map

---

src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/AppConfiguration.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/application/TkmPaymentInstrumentService.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/application/command/TkmRevokeCommand.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/application/command/TkmUpdateCommand.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/domain/services/InstrumentRevokeNotificationService.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/TestUtils.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/application/EnrolledPaymentInstrumentServiceTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/application/TkmPaymentInstrumentServiceTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/configs/ApplicationTestConfiguration.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/configs/KafkaTestConfiguration.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/configs/MongodbIntegrationTestConfiguration.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrustructure/persistence/EnrolledPaymentInstrumentRepositoryTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrustructure/persistence/TkmPaymentInstrumentServiceIntegrationTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/ports/event/KafkaEnrolledInstrumentEventsAdapterTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/ports/event/KafkaTkmTokenUpdateEventsAdapterTest.java

This PR adds the tkm application service to handle tkm update and revoke command. RevokeCommand and UpdateCommand are abstraction over TKM event which will be converted to a command for this microservice. Also adds unit test to application service and narrow integration with downstream repository

[RTD-633] Added TKM service logic and tests

---

manifests/deployment.yml

This PR adds revoke queue connection string to k8s deployment manifest.

[RTD-722] Added revoke connection string to k8s manifest

---

src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/AppConfiguration.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/KafkaConfiguration.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/KafkaRevokeNotificationService.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/RevokeNotification.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/ports/event/dto/TokenManagerCardChanged.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/ports/event/routes/PaymentInstrumentEventRouter.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/ports/rest/KafkaRestController.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/KafkaRevokeNotificationServiceTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/ports/event/ApplicationEnrollEventAdapterTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/ports/event/routes/PaymentInstrumentEventRouterTest.java
src/test/resources/application-test.yml

This PR adds a revoke notification producer, which send a revoke message to all applications (like IDPAY) starting from a TKM revoke event
- implemented kafka producer which produce events to rtd-revoked-pi queue
- improved router payload parsing
- narrow integration test for kafka producer

[RTD-723] Added simple revoke producer implementation

---

src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/ports/event/dto/HashTokenChangeType.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/ports/event/dto/TokenManagerCardChanged.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/TestUtils.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/splitter/TokenManagerWalletEventSplitterTest.java

fix: [RTD-708] Handle tkm event date format

---

pom.xml
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/configurations/AppConfiguration.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/domain/services/ChainRevokeNotificationService.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/BPDRevokeNotificationService.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/domain/services/ChainRevokeNotificationServiceTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/BPDRevokeNotificationServiceTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/KafkaRevokeNotificationServiceTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/persistence/TkmPaymentInstrumentServiceIntegrationTest.java

This PR adds a backward BPD rest api which is called by PIM when a card is deleted. Now when a card is revoked PIM takes 2 actions, notify BPD and publish over kafka queue to notify applications (like IDPAY)
- added ChainRevokeNotificationService class which allows to handle a notification chain (composed by kafka and bpd rest)
- added BPDRevokeNotificationService. Is the rest api client to BPD
- added narrow integration test by using wiremock
- unit test over chain

[RTD-746] Added bpd rest client to notify revoke

---

.github/workflows/pr-title.yml
.github/workflows/release.yml
manifests/deployment.yml

This PR adds new secret refs to k8s deployment manifest

chore: [RTD-758] Added secrets to new queues

---

src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/domain/services/EnrollAckService.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/ack/EnrollAck.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/ack/KafkaEnrollAckService.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/TestKafkaConsumerSetup.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/ack/KafkaEnrollAckServiceTest.java
src/test/resources/application-test.yml

This PR adds a kafka producer to send enroll ack events by following a cloud event schema like
- added kafka enroll ack service implementation to publish over queue
- make producer to rtd-app sync and idempotence with ack all
- make integration test for kafka enroll ack service
- simplified consumer test setup by refactoring into a single class

chore: [RTD-777] Enroll Ack kafka producer

---

src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/ack/EnrollAck.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/revoke/RevokeNotification.java

This PR fix the wrong "hashPan" key json and refactor it into "hpan"

fix: Move hashpan json key to hpan over revoke and ack payload

---

manifests/deployment.yml
pom.xml
postman/enrolled_pim.postman_collection.json
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/application/EnrolledPaymentInstrumentService.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/application/TkmPaymentInstrumentService.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/application/command/EnrollPaymentInstrumentCommand.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/configurations/AppConfiguration.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/domain/PaymentInstrumentError.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/domain/entities/EnrolledPaymentInstrument.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/domain/entities/InstrumentTokenInfo.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/domain/entities/PaymentInstrumentEnrolled.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/domain/entities/PaymentInstrumentState.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/domain/services/InstrumentTokenFinder.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/tkm/TkmClient.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/tkm/TkmInstrumentResponse.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/tkm/TkmTokenFinder.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/ports/event/dto/TokenManagerCardChanged.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/application/EnrolledPaymentInstrumentServiceTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/application/TkmPaymentInstrumentServiceTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/configs/KafkaTestConfiguration.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/domain/PaymentInstrumentTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/persistence/EnrolledPaymentInstrumentRepositoryTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/persistence/TkmPaymentInstrumentServiceIntegrationTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/tkm/TkmTokenFinderTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/tkm/TokenFinderTkmClientTest.java

feat: [RTD-1109] get tkm par/token

---

helm/rtd/.helmignore
helm/rtd/Chart.yaml
helm/rtd/values-dev.yaml
helm/rtd/values-prod.yaml
helm/rtd/values-uat.yaml
helm/rtd/values.yaml

chore: [RTD-1060] add helm chart

---

.devops/cstar-rtd-code-review-pipelines.yml
.devops/cstar-rtd-deploy-pipelines.yml

This PR adds new devops pipeline to deploy to new aks

chore: [RTD-1061] add new devops pipelines

---

helm/rtd/values-dev.yaml
helm/rtd/values.yaml
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/configurations/AppConfiguration.java

fix: [RTD-1063] update secret ref to new tkm subscription api key

---

helm/rtd/values-dev.yaml
helm/rtd/values.yaml
postman/enrolled_pim.postman_collection.json
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/configurations/AppConfiguration.java

Deploy to UAT

---

Dockerfile

This PR proposes to bump Application Insights agent version.

chore: [RTD-1220] Bump Application Insights agent version

---

src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/ack/KafkaEnrollAckService.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/revoke/KafkaRevokeNotificationService.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/TestKafkaConsumerSetup.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/ack/KafkaEnrollAckServiceTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/revoke/KafkaRevokeNotificationServiceTest.java

This PR enables producer to rtd-to-app to use proper partition count

feat: Add producer partition count

---

src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/ack/KafkaEnrollAckService.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/revoke/KafkaRevokeNotificationService.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/TestKafkaConsumerSetup.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/ack/KafkaEnrollAckServiceTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/revoke/KafkaRevokeNotificationServiceTest.java

* add producer partition key
* fix env variable partition count

feat: Add producer partition count (#76)

---

src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/ack/KafkaEnrollAckService.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/revoke/KafkaRevokeNotificationService.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/TestKafkaConsumerSetup.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/ack/KafkaEnrollAckServiceTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/revoke/KafkaRevokeNotificationServiceTest.java

* add producer partition key
* fix env variable partition count

feat: Add producer partition count (#76) (#77)

---

src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/domain/entities/EnrolledPaymentInstrument.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/domain/entities/PaymenInstrumentExported.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/domain/entities/PaymentInstrumentExported.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/ack/KafkaEnrollAckService.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/revoke/KafkaRevokeNotificationService.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/persistence/mongo/EnrolledPaymentInstrumentEntity.java
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/persistence/repositories/mapper/EnrolledPaymentInstrumentMapper.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/TestKafkaConsumerSetup.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/domain/PaymentInstrumentTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/ack/KafkaEnrollAckServiceTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/revoke/KafkaRevokeNotificationServiceTest.java

feat: [RTD-1390] exported model update

---

.devops/cstar-rtd-deploy-pipelines.yml

chore: enable prod deploy pipeline

---

.github/workflows/generate-doc-api.yml
specs/asyncapi.yml

chore: async api spec

---

helm/rtd/values.yaml

fix: [RTD-1458] Fix AppInsights problem

---

helm/rtd/values-uat.yaml
src/main/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/configurations/KafkaConfiguration.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/ports/event/ApplicationInstrumentEventAdapterTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/ports/event/ExportEventAdapterTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/ports/event/TokenManagerEventAdapterTest.java

chore: bypass export ack uat

---

.github/workflows/release.yml

chore: [RTD-1527] update checkout version

---

.devops/cstar-rtd-deploy-pipelines.yml
.github/workflows/anchore.yml
Dockerfile
helm/rtd/Chart.yaml
helm/rtd/values.yaml

This PR proposes to update the paths that trigger the deploy pipeline, including helm and Dockerfile.
- update trigger pipeline
- update chart to 2.8.0
- change docker image

chore: [RTD-1568] update trigger deploy pipeline

---

.devops/cstar-rtd-deploy-pipelines.yml
.github/workflows/anchore.yml
.github/workflows/release.yml
Dockerfile
helm/rtd/Chart.yaml
helm/rtd/values.yaml

chore: Promotion to UAT

---

src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/TestUtils.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/ack/KafkaEnrollNotifyServiceTest.java
src/test/java/it/gov/pagopa/rtd/ms/enrolledpaymentinstrument/infrastructure/kafka/revoke/KafkaRevokeNotificationServiceTest.java

fix: Promotion to UAT

---

postman/enrolled_pim.postman_collection.json

chore: update postman collection (#102)

---

.github/workflows/anchore.yml
.github/workflows/generate-doc-api.yml
.github/workflows/pr-title.yml
.github/workflows/release.yml
Dockerfile
pom.xml

fix: [RTD-1738] pinning actions and docker images

---

.github/workflows/anchore.yml
.github/workflows/generate-doc-api.yml
.github/workflows/pr-title.yml
.github/workflows/release.yml
Dockerfile
pom.xml

Reverts pagopa/rtd-ms-enrolled-payment-instrument#107

Revert "fix: [RTD-1738] pinning actions and docker images"

---

.github/workflows/anchore.yml
.github/workflows/generate-doc-api.yml
.github/workflows/pr-title.yml
.github/workflows/release.yml
Dockerfile
pom.xml

fix: [RTD-1738] pinning images

---

.github/workflows/anchore.yml
.github/workflows/generate-doc-api.yml
.github/workflows/pr-title.yml
.github/workflows/release.yml
Dockerfile
pom.xml

fix: Promotion to Prod - pinning

---

.github/CODEOWNERS
.github/workflows/generate-doc-api.yml

This PR proposes to fix the commit sha pinned in async api action.

chore: [RTD-1797] fix pinning async api

---

.github/CODEOWNERS
.github/workflows/generate-doc-api.yml

- fix pinning
- update codeowners
[RTD-1797]: https://pagopa.atlassian.net/browse/RTD-1797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1797]: https://pagopa.atlassian.net/browse/RTD-1797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1797]: https://pagopa.atlassian.net/browse/RTD-1797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1797]: https://pagopa.atlassian.net/browse/RTD-1797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1797]: https://pagopa.atlassian.net/browse/RTD-1797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1797]: …

chore: Promotion to UAT - fix pinning
